import numpy as np
import math
import time
import random
import io
import sys
import re
from tqdm import tqdm
import matplotlib.pyplot as plt

# Import the exact working simulation scripts
from simulate_semantic_capacity import simulate_semantic_capacity
from simulate_hop2_branching import simulate_hop2_branching

from utils.data_processing import get_data
from utils.utils import get_neighbor_finder, RandEdgeSampler, MultiLayerTemporalCache

def extract_theoretical_parameters(dataset_name):
    """Runs the imported simulation scripts and captures their outputs to derive optimal capacities."""
    print(f"Running theoretical simulations for {dataset_name}...")
    
    # Reroute standard output to capture the print statements from the imported scripts
    captured_output = io.StringIO()
    original_stdout = sys.stdout
    sys.stdout = captured_output
    
    try:
        simulate_semantic_capacity(dataset_name)
        simulate_hop2_branching(dataset_name)
    finally:
        sys.stdout = original_stdout
        
    output_text = captured_output.getvalue()
    
    # Parse the exact empirical metrics generated by the scripts
    p95_unique = float(re.search(r'95th Percentile - Unique Neighbors.*?: ([\d\.]+)', output_text).group(1))
    p95_total = float(re.search(r'95th Percentile - Total Active Edges.*?: ([\d\.]+)', output_text).group(1))
    multiplier = float(re.search(r'Empirical Multiplier: ([\d\.]+)x', output_text).group(1))
    
    # Calculate mathematically optimum parameters
    # C1 applies the 1.75x FIFO burst absorber to the semantic limit
    c1_opt = int(round(p95_unique * 1.75))
    # C2 applies the exact empirical temporal branching factor
    c2_opt = int(round(c1_opt * multiplier))
    
    print("\n--- Dynamically Calculated Optimums ---")
    print(f"P95 Unique (Semantic Limit): {p95_unique}")
    print(f"P95 Total (Raw Volume): {p95_total}")
    print(f"Branching Multiplier: {multiplier}x")
    print(f"Derived Optimum Capacity -> C1: {c1_opt}, C2: {c2_opt}\n")
    
    return int(p95_unique), int(p95_total), multiplier, c1_opt, c2_opt

def calculate_set_metrics(base_list, cache_list):
    """Calculates Recall, Precision, and Jaccard IoU for two sets of edges."""
    base_set = set(base_list)
    cache_set = set(cache_list)
    
    intersect = len(base_set.intersection(cache_set))
    union = len(base_set.union(cache_set))
    
    recall = intersect / len(base_set) if len(base_set) > 0 else 1.0
    precision = intersect / len(cache_set) if len(cache_set) > 0 else 1.0
    iou = intersect / union if union > 0 else 1.0
    
    return recall, precision, iou

def evaluate_configuration(dataset_name, train_data, train_sampler, base_finder, c1, c2, batch_size=200):
    layer_finder = get_neighbor_finder(train_data, uniform=False, use_layered_cache=True)
    
    hop_capacities = {1: c1, 2: c2}
    layer_finder.cache = MultiLayerTemporalCache(max_edges_per_hop=hop_capacities)
    
    metrics = {'recall': [], 'prec': [], 'iou': [], 'latency_ms': []}
    
    num_instance = len(train_data.sources)
    # Evaluate on a 20% sample of batches for fast verification
    num_batch = math.ceil((num_instance * 0.2) / batch_size) 
    
    for k in tqdm(range(num_batch), desc=f"Eval C1={c1}, C2={c2}", leave=False):
        start_idx = k * batch_size
        end_idx = min(num_instance, start_idx + batch_size)
        
        sources = train_data.sources[start_idx:end_idx]
        destinations = train_data.destinations[start_idx:end_idx]
        timestamps = train_data.timestamps[start_idx:end_idx]
        edge_idxs = train_data.edge_idxs[start_idx:end_idx]
        
        size = len(sources)
        _, negatives = train_sampler.sample(size)
        
        base_pos = base_finder.extract_enclosing_subgraph(sources, destinations, timestamps, y=1, use_cache=False)
        random.seed(42)
        base_neg = base_finder.extract_enclosing_subgraph(sources, negatives, timestamps, y=0, use_cache=False)
        
        start_time = time.perf_counter()
        layer_pos = layer_finder.extract_enclosing_subgraph(sources, destinations, timestamps, y=1, use_cache=True)
        random.seed(42)
        layer_neg = layer_finder.extract_enclosing_subgraph(sources, negatives, timestamps, y=0, use_cache=True)
        
        batch_latency_ms = (time.perf_counter() - start_time) * 1000 / (size * 2)
        metrics['latency_ms'].append(batch_latency_ms)
        
        for i in range(size):
            for b_data, l_data in [(base_pos[i], layer_pos[i]), (base_neg[i], layer_neg[i])]:
                b_edges, l_edges = b_data.edge_time.tolist(), l_data.edge_time.tolist()
                e_rec, e_prec, e_iou = calculate_set_metrics(b_edges, l_edges)
                metrics['recall'].append(e_rec)
                metrics['prec'].append(e_prec)
                metrics['iou'].append(e_iou)

        for s, d, t, e_idx in zip(sources, destinations, timestamps, edge_idxs):
            layer_finder.cache.push_edge(s, d, t, e_idx, layer_finder)

    return {k: np.mean(v) for k, v in metrics.items()}

def plot_degradation(results, dataset_name):
    """Generates a dual-axis bar/line plot to visualize performance degradation."""
    labels = [f"{r[0].split(' (')[0]}\nC={r[1]},{r[2]}" for r in results]
    recalls = [r[3] for r in results]
    precs = [r[4] for r in results]
    ious = [r[5] for r in results]
    latencies = [r[6] for r in results]
    
    x = np.arange(len(labels))
    width = 0.25
    
    fig, ax1 = plt.subplots(figsize=(15, 7))
    
    rects1 = ax1.bar(x - width, recalls, width, label='Edge Recall', color='#2ca02c', alpha=0.85)
    rects2 = ax1.bar(x, precs, width, label='Edge Precision', color='#d62728', alpha=0.85)
    rects3 = ax1.bar(x + width, ious, width, label='Jaccard IoU', color='#1f77b4', alpha=0.95)
    
    ax1.set_ylabel('Fidelity Score [0.0 - 1.0]', fontsize=11)
    ax1.set_title(f'Multi-Layer Cache Optimization & Degradation: {dataset_name}', fontsize=14, pad=15)
    ax1.set_xticks(x)
    ax1.set_xticklabels(labels, fontsize=10)
    ax1.set_ylim([min(ious) - 0.05, max(max(recalls), max(precs)) + 0.05])
    ax1.grid(axis='y', linestyle=':', alpha=0.7)
    
    for rect in rects3:
        height = rect.get_height()
        ax1.annotate(f'{height:.3f}',
                     xy=(rect.get_x() + rect.get_width() / 2, height),
                     xytext=(0, 3), textcoords="offset points",
                     ha='center', va='bottom', fontsize=9, fontweight='bold', color='#1f77b4')

    ax2 = ax1.twinx()
    ax2.plot(x, latencies, color='purple', marker='D', linestyle='-', linewidth=2.5, markersize=8, label='Extraction Latency (ms)')
    ax2.set_ylabel('Mean Latency (ms / subgraph)', color='purple', fontsize=11)
    ax2.tick_params(axis='y', labelcolor='purple')
    
    lines_1, labels_1 = ax1.get_legend_handles_labels()
    lines_2, labels_2 = ax2.get_legend_handles_labels()
    ax1.legend(lines_1 + lines_2, labels_1 + labels_2, loc='upper right', bbox_to_anchor=(0.98, 0.95))
    
    plt.tight_layout()
    plt.savefig("cache_optimum_degradation_plot.png", dpi=300)
    print("\nVisualization saved to 'cache_optimum_degradation_plot.png'")

def main():
    dataset_name = "calls"
    _, _, _, train_data, _, _, _, _ = get_data(dataset_name)
    
    base_finder = get_neighbor_finder(train_data, uniform=False, use_layered_cache=False)
    train_sampler = RandEdgeSampler(train_data.sources, train_data.destinations)
    
    # Dynamically extract parameters using the imported scripts
    p95_unique, p95_total, multiplier, c1_opt, c2_opt = extract_theoretical_parameters(dataset_name)
    
    configurations = [
        ("Semantic Limit (Under-Cap)", p95_unique, int(round(p95_unique * multiplier))),
        ("Calculated Optimum (Peak)", c1_opt, c2_opt),
        ("Raw Limit (Over-Cap)", p95_total, int(round(p95_total * multiplier))),
        ("Optimum C1, Flat C2", c1_opt, c1_opt),
        ("Optimum C1, Bloated C2", c1_opt, int(round(c1_opt * 5.0)))
    ]
    
    print(f"{'Configuration':<35} | {'C1':<3} | {'C2':<4} | {'Recall':<6} | {'Prec':<6} | {'IoU':<6} | {'Latency(ms)':<8}")
    print("-" * 85)
    
    results = []
    for name, c1, c2 in configurations:
        res = evaluate_configuration(dataset_name, train_data, train_sampler, base_finder, c1, c2)
        results.append((name, c1, c2, res['recall'], res['prec'], res['iou'], res['latency_ms']))
        print(f"{name:<35} | {c1:<3} | {c2:<4} | {res['recall']:.4f} | {res['prec']:.4f} | {res['iou']:.4f} | {res['latency_ms']:.4f}")

    plot_degradation(results, dataset_name)

if __name__ == "__main__":
    main()